import React from 'react';

export default function Interpretation() {
  return (
    <div className="prose dark:prose-invert">
      <h2>Interpreting EQAlert Results</h2>
      <p>
        This guide explains how to read the tables and charts generated by EQAlert.
        Bias values indicate the difference between a device result and the group
        or sample mean. Limits of agreement (LoA) show the range within which most
        differences should fall.
      </p>
      <h3>Bias Tables</h3>
      <p>
        Each row displays the measured value, the reference mean, and the
        resulting bias. Rows highlighted red exceed your configured threshold.
      </p>
      <h3>Bland-Altman Plot</h3>
      <p>
        Points represent the difference between two devices plotted against their
        mean result. The central line is the bias while the dotted lines are the
        upper and lower LoA (bias ±1.96 SD). Samples outside these lines may
        indicate poor agreement or outliers.
      </p>
      <h3>Next Steps</h3>
      <ul>
        <li>Check calibration and QC records for devices with large bias.</li>
        <li>Repeat testing of failed samples where possible.</li>
        <li>Review method differences between laboratory and POCT protocols.</li>
        <li>Consult your EQA provider guidelines for analyte-specific actions.</li>
      </ul>
    </div>
  );
}
